### ISSUE TITLE
Allow for struct MetricHandlers

### ISSUE THREAD

**Issue by MrLotU** [apple/swift-metrics#32]
Currently, `MetricHandlers` are declared as follows (taking `TimerHandler` as an example here)
```swift
public protocol TimerHandler: AnyObject {
    /// Record a duration in nanoseconds.
    ///
    /// - parameters:
    ///     - value: Duration to record.
    func recordNanoseconds(_ duration: Int64)
}
```
where they conform to `AnyObject` specifying they have to be classes.
The reasoning behind this can be found on the forums:
> by forcing them to be classes, we can reduce their memory footprint, and there is no real advantage of allowing them to be structs as they don't carry state
(https://forums.swift.org/t/metrics/19353/4)

I however, did run into a case where (IMO) it'd be nicer & cleaner to have them be `struct`s.

I'd like to propose the following solution as a workaround: 

```swift
public protocol BaseTimerHandler {
    /// Record a duration in nanoseconds.
    ///
    /// - parameters:
    ///     - value: Duration to record.
    func recordNanoseconds(_ duration: Int64)
}

public protocol TimerHandler: BaseTimerHandler, AnyObject { }
```
Where users should be encouraged to use `TimerHandler` instead of `BaseTimerHandler`, but the rest of the flow can use `BaseTimerHandler` and handle both classes and structs.

Please let me know what you think. If the overall consensus is that this'd be a good addition/change, I'll open up a PR 😄

**Comment by Mordil** [comment]
To facilitate more useful debate - could you share the use case you ran into?

**Comment by ktoso** [comment]
Right, could you provide the use-case / sample code you have in mind?

**Comment by MrLotU** [comment]
I definitely can. Will do once back at a machine 😃

**Comment by MrLotU** [comment]
So, here is the usecase; I'm working on my Prometheus backend, and the way Prometheus works with labels & the way the metrics library does conflicts. Prometheus requires you to have a specific set of label keys set beforehand, whereas the metrics library allows you to pass them in when creating the metric.

Example:
```swift
// Prometheus
struct MyLabels: MetricLabels {
   var identifier: String = "*"
}

let counter = myProm.createCounter(
     forType: Int64.self,
     named: "my_counter",
     withLabelType: MyLabels.self)

counter.inc(12, labels: MyLabels(identifier: "123"))

// Metrics
let counter = Counter(label: "my_counter", dimensions: [("identifier", "123")])
```

The reason I would like for the `MetricHandlers` to be structs is because I'd like them, instead of being the actual counter, be a thin wrapper around it. This way you could have more than 1 `CounterHandler` pointing to the same `PromCounter` & pass the labels to the `PromCounter` whenever `Counter.increase` is called.

I created a start of this implementation at https://github.com/MrLotU/SwiftPrometheus/tree/MetricsLib 😄

**Comment by MrLotU** [comment]
Discussed this issue with @weissi and turns out there is no benefit for using Structs over Classes, so I will close this issue 😃
