### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by tomerd** [apple/swift-metrics#5]
originally brought up by @weissi 

We should think about integer overflows, kinda likely to happen with metrics and you wouldn’t want to crash for metrics.

We could check for them explicitly or use &+ and friends instead of + but that’s only defined behaviour for unsigned ints I think (that’s how it is in C , overflow defined for unsigned and undefined for signed ints).

This is just to remind us to think about it and write tests.

Nio has examples for overflow tests: https://github.com/apple/swift-nio/blob/06649bb8c704a042fc07f2013ae429e2d646e7bb/Tests/NIOTests/ByteBufferTest.swift#L938

**Comment by milseman** [comment]
Which is the lesser of evils here? On wrapping, is it worse to have a counter/metric that goes negative/zero than a trap? Could that lead to a loss of data or a more serious security violation?

**Comment by weissi** [comment]
> Which is the lesser of evils here? On wrapping, is it worse to have a counter/metric that goes negative/zero than a trap? Could that lead to a loss of data or a more serious security violation?

Wrap would definitely be the lesser evil. Metrics are usually egress only, so the emitting program usually doesn't depend on them at all, it shouldn't have any visible effects on the program itself. So crashing for metrics would be pretty bad I think.

**Comment by weissi** [comment]
one question is though if we should maybe send the metrics backend a notification 'by the way, this just overflowed' or so

**Comment by Lukasa** [comment]
Perhaps that notification should log. :wink:

**Comment by weissi** [comment]
> Perhaps that notification should log. 😉

And increase the 'overflow counter metric' haha.

**Comment by tomerd** [comment]
etoomanydependencies

**Comment by tomerd** [comment]
joking aside, i guess we should choose between 
a. capping at max
b. resetting to zero

i slightly prefer a, since b could throw off percentiles calculations and related alerts in a more significant way

**Comment by milseman** [comment]
> Metrics are usually egress only, so the emitting program usually doesn't depend on them at all, it shouldn't have any visible effects on the program itself

This suggests a saturating add, as @tomerd prefers

**Comment by weissi** [comment]
very happy with capping at .max

**Comment by milseman** [comment]
> * cap at max: 👍

The theoretical downside of this approach would be in code that assumed that increment always had some observable effect.

**Comment by MrLotU** [comment]
> The theoretical downside of this approach would be in code that assumed that increment always had some observable effect.

Agreed, though I'd be impressed if anyone actually hit the max of an Int64. Unless of course for some reason your initial value is `Int64.max - 2` 😄

**Comment by weissi** [comment]
> > * cap at max: 👍
> 
> The theoretical downside of this approach would be in code that assumed that increment always had some observable effect.

Well, metrics (just like logging) isn't meant for the application to observe the metrics but rather to _report_ the metrics to elsewhere. In other words, adding/removing metrics code should never have an effect on your app.

**Comment by tomerd** [comment]
closed via #19
