### ISSUE TITLE
Release notes for 2.x should do a better job explaining what happened

### ISSUE THREAD

**Issue by weissi** [apple/swift-metrics#66]
I think the release notes for 2.0.0 should make it more clear what exactly happened. Because swift-metrics is an API package, issuing a new major could easily lead to an ecosystem split which we should really avoid so it's important everybody understands. I filed the following issues with known dependents:

- https://github.com/vapor/postgres-nio/issues/87
- https://github.com/amzn/smoke-aws/issues/44
- https://github.com/amzn/smoke-framework/issues/42
- https://github.com/amzn/smoke-http/issues/50
- https://gitlab.com/Mordil/swift-redi-stack/issues/70
- https://github.com/apple/swift-statsd-client/issues/15
- https://github.com/allegro/swiftbox/issues/10
- https://github.com/MrLotU/SwiftPrometheus/issues/30
- https://github.com/allegro/swiftbox-metrics-statsd/issues/2
- https://github.com/vapor/vapor/issues/2213
- https://github.com/skelpo/SkelpoMetrics/issues/1
- https://github.com/swiftyserver/SwiftyServer/issues/2
- https://github.com/jsloop42/TeaPotServer/issues/1
- https://github.com/MrLotU/SwiftHooks/issues/4
- https://github.com/mengxiangyue/flake/issues/1
- https://github.com/OpenKitten/MongoKitten/issues/225
- https://github.com/aaronjedwards/swift-tds/issues/6
- https://github.com/t089/MicroHttp/issues/1

**Comment by weissi** [comment]
CC @tomerd

**Comment by tomerd** [comment]
thanks @weissi

**Comment by weissi** [comment]
That’s perfect. Thank you!
