### ISSUE TITLE
Foundation usage

### ISSUE THREAD

**Issue by normanmaurer** [apple/swift-metrics#8]
As I did not follow the whole discussion around the API I was wondering if we really want to put the requirement that you need to use Foundation:

https://github.com/apple/swift-metrics/blob/0b2fb92ce969b1de438535a3d13c735262e3a8db/Sources/Metrics/Metrics.swift#L17

Wouldn't it be better to make this an implementation detail ?

**Comment by tomerd** [comment]
@normanmaurer wdyt?

**Comment by normanmaurer** [comment]
@tomerd sounds good to me
